## master config
component:
  template:
    tfvars:
      s3_bucket_name: www.terrahub.io

build:
  env:
    variables:
      THUB_ENV: master
      THUB_S3_PATH: s3://www.terrahub.io
      THUB_ROBOTS: ../../robots.master.txt
      THUB_MAX_AGE: 31536000
