project:
  name: TerraHub_Website
  code: 2ae8103c
  include:
    - .terrahub
  exclude:
    - '**/node_modules/**'
    - '**/.terraform/**'
    - '**/.git/**'
template:
  locals:
    region: us-east-1
    account_id: 123456789000
  terraform:
    backend:
      s3:
        key: >-
          terraform/mitocgroup/terrahub-www/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
        workspace_key_prefix: terraform_workspaces
        bucket: data-lake-terrahub-us-east-1
        region: us-east-1
    required_providers:
      aws:
        source: hashicorp/aws
        version: 3.26.0
  provider:
    aws:
      region: local.region
      allowed_account_ids:
        - local.account_id
terraform:
  varFile:
    - default.tfvars
  version: 0.12.24
