## stage config
component:
  template:
    tfvars:
      remote_state_key: terraform_workspaces/stage/terraform/mitocgroup/terrahub-www/s3_bucket/terraform.tfstate
      aliases: [www-stage.terrahub.io]
      comment: www-stage.terrahub.io
      origin_id: S3-Website-www-stage.terrahub.io.s3-website-us-east-1.amazonaws.com
      origin_name: www-stage.terrahub.io.s3-website-us-east-1.amazonaws.com

## build config
build:
  env:
    variables:
      THUB_S3_BUCKET_NAME: www-stage.terrahub.io
